### PR TITLE
compile on macOS

### PR DESCRIPTION
**Pull request by simongray**
I've made some changes that make it possible to compile on macOS (and added output files to .gitignore). It results in a `cstlemma` binary file, but several warnings of this sort occur during compilation:

```
warning: struct 'optionStruct' was previously declared as a class; this is valid, but may result in linker errors under the Microsoft C++ ABI
      [-Wmismatched-tags]
```

I tried running the example code in the README:

```
touch my_empty_rule_file
./cstlemma -L -f my_empty_rule_file -i my_text_file.txt
```

which returns 

```
Segmentation fault: 11
```

So clearly something isn't working.

### CODE REVIEW

**Comment by simongray** [comment]
It's running, but it doesn't work for `make all` only `make`, since macOS doesn't really support static linking (for security reasons, I think). I think it's technically possible to statically compiles code on macOS, but they make it really laborious.

Currently, the [makecstlemma.bash script](https://github.com/kuhumcst/cstlemma/blob/master/doc/makecstlemma.bash#L47) calls `make all` rather than `make` (which only does dynamic linking since that is the default target). What do you suggest I do about it? Change it `make`?

**Comment by BartJongejan** [comment]
The makecstlemma.bash script was never meant to be used more than once. I guess it should have a different name to reflect that. The script exists to make it easy to get cstlemma compiled and linked the first time. Thereafter, the thinking was, the developer would use `git pull' , `cd src', `make' etc. 
makecstlemma.bash ensures that a number of repos exist and then goes on to make the lemmatiser. Only one of these repos is solely dedicated to cstlemma. The others are used by other tools as well. The idea was that I wanted to organize all git based projects in the same folder, "<home>/gitprojects", so projects always would "know" were to find source code that was shared with other projects: those shared repos would be at the **_same_** level as the projects proper.
I think the best way to make makecstlemma.bash reusable is to let it test whether the sought-for repos exist two levels higher up:
     if [-d ../../hashmap ]; then
        ....
     elif [! -d hashmap ]; then
        ....
     fi

A propos static linking: is there a way for a script to check whether it is working under macOS?

**Comment by simongray** [comment]
@Bart please see the changes in this latest commit. It should allow you to keep your present workflow.

**Comment by simongray** [comment]
@BartJongejan please see the changes in this latest commit. It should allow you to keep your present workflow.

**Pull request merged**
